# Generated by Django 4.2.5 on 2023-09-20 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0003_alter_vote_options_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(default='inne - podaj / kino nowe horyzonty / budynek A1 PWR, sala 329', max_length=255)),
                ('date_status', models.CharField(blank=True, choices=[('UNKNOWN', 'KIEDYŚ'), ('NOW', 'TERAZ'), ('PAST', 'BYŁO'), ('FUTURE', 'BĘDZIE')], default='UNKNOWN', max_length=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='events', to='movie.movie')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
