# Generated by Django 4.2.5 on 2023-09-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',), 'verbose_name_plural': 'Nasze wydarzenia'},
        ),
    ]
