# Generated by Django 4.2.5 on 2023-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name_plural': 'Oceny'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, default='movies_thumbnails/logo.png', null=True, upload_to='movies_thumbnails'),
        ),
    ]
