# Generated by Django 4.2.5 on 2023-10-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_vote_options_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='comment_about_the_movie',
            new_name='comment',
        ),
    ]
